import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body className="w-full h-full mx-0 p-0 bg-white">
        <div className="flex flex-col min-h-screen">
          <Navbar />
          <main className="pt-10 2xl:pt-14 xl:pt-12 lg:pt-12 md:pt-10 sm:pt-10 flex-1 bg-blue">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
